name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deploy/firephenix-backend
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart firephenix-flask
            sudo systemctl restart firephenix-bot